version: '3.8'

services:
  print-hub:
    build: .
    image: yudilee/print-hub:latest
    container_name: print-hub
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - APP_NAME=PrintHub
      - APP_ENV=production
      - APP_KEY=${APP_KEY:-base64:19hjIjrPouxH0sSc7OKp+Z7wjIYlDEWP5kfbYpKC7fY=}
      - APP_DEBUG=false
      - APP_URL=http://localhost:8082
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=file
      - CACHE_STORE=file
      - QUEUE_CONNECTION=sync
    volumes:
      - print-hub-storage:/var/www/html/storage
      - print-hub-database:/var/www/html/database

volumes:
  print-hub-storage:
  print-hub-database:
